### ISSUE TITLE
Allow users to add multiple schemas

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#192]
At the moment, we only allow one schema per dataset. It might be nice to be able to specify multiple schemas, so we can have multiple types of data within a dataset, which is definitely a legitimate thing to have.

**Comment by Floppy** [comment]
Use case: So that reference data can be published alongside data, and support for multiple data types within a dataset.

**Comment by jamesjefferies** [comment]
This implies a link from DatasetFile to Schema rather than Dataset to Schema right? So you'd add a reference data file say, with it's own Schema, then a set of data data with a different schema.

**Comment by Floppy** [comment]
Yes, that's true.

**Comment by jamesjefferies** [comment]
A reminder to myself that if adding, say 3 files, with the same schema - then if adding at file level, the schema needs to persist immediately rather than later, so that the drop down can then be updated with that latest schema. You wouldn't want the same schema uploading multiple times..

**Comment by jamesjefferies** [comment]
In a related thought - does this all need to work without JS?

**Comment by jamesjefferies** [comment]
The file name for the schemas will be the schema name, followed by schema. So for a schema file with the name ```My Amazing schema``` - the file name will be ```my-amazing-schema-schema.json``` - which, now I've typed it *does* look a bit silly, but I think it make sense.

**Comment by Floppy** [comment]
We could perhaps use `my-amazing-schema.schema.json` as a way to distringuish the two?

**Comment by jamesjefferies** [comment]
@Floppy one of the crunches I've hit whilst working on this is *updating* DatasetFiles as I've been working on the schema changes. I made an assumption which was *wrong*, which was that editing allows similar functionality to adding, i.e you might want to change the schema. I was looking at the tests rather than looking at the UI to see how it currently works. Doh.

So, to get to the point where this issue can be closed and I can raise a Change Request, can we agree that this existing editing functionality remains *as is* and we don't include editing with schemas for now?

### Current Editing functionality

Currently when editing a Dataset you can change:

Description
Publisher Name
Publisher URL
License
Frequency

Then for the Dataset File section you can change

DatasetFile Description
The actual file

And you can 

Add a new file

**Comment by jamesjefferies** [comment]
And yes @Floppy the ```my-amazing-schema.schema.json``` is a much better idea!

**Comment by Floppy** [comment]
Yeah, I think changing a schema for an existing file is one we can leave out for now. Can you add a new file with a schema during edit?

**Comment by jamesjefferies** [comment]
Not at the moment - would make life easier to keep it that way too *for now*

**Comment by Floppy** [comment]
That's fine. Incremental steps :)

**Comment by jamesjefferies** [comment]
This change, for adding schemas per datafile is now live.
