### ISSUE TITLE
Open Data Certificate generation not working?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#193]
I'm confused by:
- Issue #1 Integration with Open Data Certificates being open
- PR #169 Generate Open Data Certificate being closed
- Trello [Auto-generate certificates for Octopub uploads](https://trello.com/c/iaZPw5On) being done
- [UK Government Cats](https://peterkwells.github.io/uk-government-cats/) data on Octopub showing a certificate.  `<script src="https://certificates.theodi.org/en/datasets/214192/certificate/badge.js"></script>`
- [Australian open data publishers](https://stephen-gates.github.io/australian-open-data-publishers/) on Octopub not showing a certificate.   `<script src=""></script>`

To earn a certificate, how does Octopub know my Open Data Certificate account? (Would a sign in to Open Data Certificates using your GitHub account help?)

How does Octopub know what Jurisdiction to use?

**Comment by pezholio** [comment]
Hmmmm, yeah. It seems like something has gone wrong here. The certificates are being generated, but we're not getting a level. I'll look into it

**Comment by caiwilliamson** [comment]
This was a bit painful to fix so I'll document what I did here.

In the current version of Octopub (v2) the certificate generation was disabled (commented out), presumably because it was too hard to fix at the time. 

It seems that the Open Data Certificates (ODC) API issues a certificate for a published dataset by analysing its GitHub Pages site to gather information and determine a score (bronze, silver etc.). Octopub creates the certificates via the API in `app/services/jekyll_service.rb` and the process is roughly as follows (pseudocode for brevity):
```
# Initialize a certificate factory object
cert = CertificateFactory::Certificate.new(github_pages_site_url_for_the_dataset)

# Post to ODC to generate the certificate and get a response
result = cert.result

# If a valid certificate is issued, add a badge to the github pages site linking to the certificate
add_certificate_url(result[:certificate_url], dataset)
```
There were several issues:
1) Due to a broken check, Octopub doesn't wait for the GitHub Pages site to finish building before generating the certificate. 
**Solution: fix the check.**
2) ODC is extremely fussy about the format of the supplied `github_pages_site_url_for_the_dataset`. It must start with `https` and end in a trailing slash. 
**Solution: ensure the scheme is set to https and add a trailing slash.**
3) The returned certificate url starts with `http`, but it must start with `https` to resolve correctly and fetch the badge. 
**Solution: ensure the scheme is set to https.**
4) ODC apparently requires `publisher_name` and `github_url` to be present on the GitHub Pages site or the certificate generation will fail. We removed these form fields in Octopub v2, but the model attributes still exist. 
**Solution: Populate the attributes with `@dataset.owner` and `@dataset.github_url` since they are always present and relevant.**

Note: Certificate badges sometimes take a few seconds/minutes to show up the first time around.
