### ISSUE TITLE
List of available schemas

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#203]
Instances of Octopub could have a list of available schemas, which are available from a dropdown in the form rather than an upload field. Upload field could be disabled, optionally. Site administrators (publishers in #201?) should be able to add to the list of available schemas.

**Comment by Floppy** [comment]
Deprecates #151

**Comment by Floppy** [comment]
Also deprecates #152. Not sure why those two were separate.

**Comment by Floppy** [comment]
Limit which schemas can be seen by which users.

**Comment by jamesjefferies** [comment]
Just wondering what you mean, how you could limit schemas for users?

**Comment by Floppy** [comment]
Yes, sorry, that was a quick note. An organisation might have a lot of schemas, but a single user might only need a couple. Ideally limit the list on a per-user basis.

**Comment by jamesjefferies** [comment]
I'm wondering if there is a specific reason why the Schema URL isn't saved with the rest of the Dataset model. I'm assuming there *isn't* a particular reason for this, in which case, I'm going to add it, but please do chip in if I'm missing something!

**Comment by Floppy** [comment]
No, I think that makes sense. Probably just wasn't needed so far.

**Comment by jamesjefferies** [comment]
There will be a small migration process for this change, to ensure new DatasetSchema entries are populated for existing uploaded datasets. Must remember!

**Comment by jamesjefferies** [comment]
At this point, we have two new bits of functionality 

1) A read only view of the user's datasets 
2) When adding dataset files, the user can select an existing schema or create a new one

Other things which may or may not be in scope could/should be:

A) when adding multiple files all with the same, but new schema, then the dropdown should be updated so that after the first file, the new schema will be available. This currently isn't the case and probably should be a new Feature/Issue.

B) Site administrators don't currently exist, but again, maybe as a separate issue, they could have Add/Delete a schema on it's own functionality.  It has the organisation/user changes as a pre-requisite.

C) #151 suggests that being in an organisation may involve a schema being mandated for all uploads, I think this would require a fair few changes and again, should be a new Feature/Issue if it is a requirement. It has the organisation/user changes as a pre-requisite.

**Comment by jamesjefferies** [comment]
I've created a workflow to add schemas separately for A and re-opened #151
