### ISSUE TITLE
View link goes to data download instead of data view

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#387]
On https://stephen-gates.github.io/australian-open-data-publishers/ when I click the view link it takes me to the .csv file download.

It should go to the data view https://stephen-gates.github.io/australian-open-data-publishers/data/australian-open-data-publishers/ 

Somehow `.csv` has been added to the link.

This bug doesn't occur on some other datasets e.g. https://stephen-gates.github.io/public-transport-schedules-for-south-east-queensland/

**Comment by jamesjefferies** [comment]
Thanks @Stephen-Gates for the heads up, I'll take a look today to work out why the tests aren't picking this up and what the problem is!

**Comment by jamesjefferies** [comment]
Just trying to set an ```update``` off to see if it fixes it. I suspect this may be a bug which has since been fixed as it was last updated over a month ago.

**Comment by jamesjefferies** [comment]
Blimmi' 'eck - it's taken me all this time, but I think I've worked out what your problem is!

This commit https://github.com/Stephen-Gates/australian-open-data-publishers/commit/fa90e05e1699cdac12df510bded241f3e752eb38#diff-eacf331f0ffc35d4b482f1d15a887d3b

amended the template so that instead it being: 
```
<td><a href="{{ resource.path | split:"." | first }}"><i class="fa fa-search"></i> View</a></td>
```
it is now
```
<td><a href="{{ resource.path | split:" . " | first }}"><i class="fa fa-search"></i> View</a></td>
```
Where there is an extra space either side of the ```.``` in the split function. So when it's generating the site, it isn't stripping the ```.csv``` from your filename. So! I think you need to manually edit your index template in github, trigger the regeneration of the Jekyll site and it will be sorted.

Please close the issue if this does fix it.

**Comment by Stephen-Gates** [comment]
@jamesjefferies fixed! Sorry to waste your time. Not sure how that happened.
