### ISSUE TITLE
Newly created github org not available when creating new dataset

### ISSUE THREAD

**Issue by rachelwilson** [theodi/octopub#952]
---------- Forwarded message ---------
From: Richard Pope <richard@memespring.co.uk>
Date: Sat, 17 Nov 2018 at 01:33
Subject: Octopub bug report
To: <info@theodi.org>

If you create a new org on github after creating signing in for the first time, the new org is not available when creating a new dataset.

All the best,

Richard

**Comment by caiwilliamson** [comment]
@rachelwilson Please provide steps to replicate.

**Comment by rachelwilson** [comment]
Hi @caiwilliamson, I didnt raise this one, Richard did.

If you're not able to reproduce this yourself using Richards description above, then I guess we can close it.

**Comment by caiwilliamson** [comment]
I'm not sure what he means. It sounds like he's saying:

1. Sign in (presumably to Octopub?)
2. Create a new org on GitHub
3. Org is not avilable when creating a new dataset

There's not much we can do about that since Octokit can only pick up the new Org when reauthenticating with GitHub, which either happens on the next page refresh or relog. I'm happy to close this one.

**Comment by rachelwilson** [comment]
Could you confirm that re-logging in does pickup the new org. If so, we can close this.
