### ISSUE TITLE
Can't assign a schema to a collection immediately after creation

### ISSUE THREAD

**Issue by rachelwilson** [theodi/octopub#953]
---------- Forwarded message ---------
From: Richard Pope <richard@memespring.co.uk>
Date: Sat, 17 Nov 2018 at 22:15
Subject: Octopub beta bug
To: <info@theodi.org>

It is not possible to assign a schema to a collection immediately after creation (suspect this is down to caching)

To recreate:

1. Create & publish collection
2. Create schema
3. Try and edit add schema to the collection

Hope that helps!

Richard

**Comment by rachelwilson** [comment]
Is this a duplicate of https://github.com/theodi/octopub/issues/885?

**Comment by richardjpope** [comment]
It looks like it, yes.

**Comment by rachelwilson** [comment]
Oh hi Richard :) We finally have some resource to tackle some of these bugs and this one is on the list. Watch this space...

**Comment by richardjpope** [comment]
Excellent!

**Comment by caiwilliamson** [comment]
To be clear this issue only applies to **published** datasets. It also appears to be intentional. A piece of code in the schema select tag (views/dataset_files/edit_form.html.erb) disables the select if the dataset is published:

`disabled: @dataset.published_status == 'published'`

I don't know why this was intended. Removing this check _appears_ to have no ill effects from my limited testing, and will allow for selecting/changing a schema on an already published dataset.

@olivierthereaux @rachelwilson Let me know if you want this change implemented or not. Is there a reason why published datasets should not have schemas added/changed?

**Comment by rachelwilson** [comment]
The only thing I can think of is that when adding a schema later it's possible that a published dataset will not pass schema validation - and perhaps we hadn't nailed down the edit-collection workflow for schemas.

What would the workflow be?  I imagine it would be
1. Edit the collection to add a schema
2. move the collection to revised status
3. the collection then needs to pass schema validation before it can be published
4. publish again

Cai, is this what becomes possible once you remove the disable check in the code?
